### ISSUE TITLE
Type 'SwinjectStoryboardOption' does not conform to protocol 'ServiceKeyOption' 

### ISSUE THREAD

**Issue by Sega-Zero** [Swinject/SwinjectStoryboard#127] opened 2019-09-04 15:38 UTC
Upgraded Swinject to 2.7.0 and `SwinjectStoryboard` now doesn't compile, with the error above.
I believe, there must be something like this in code:
```swift
internal struct SwinjectStoryboardOption: ServiceKeyOption {
    func hash(into: inout Hasher) {
        into.combine(self.controllerType)
    }
```

should I open a PR with a fix?

**Comment by AlexanderEBaranov** [comment] 2019-09-04 19:40
when this problem will fixed ?

**Comment by dvshelley** [comment] 2019-09-13 15:27
Here is the actual error.

error: type 'SwinjectStoryboardOption' does not conform to protocol 'ServiceKeyOption'
internal struct SwinjectStoryboardOption: ServiceKeyOption {
                ^
..... /Carthage/Checkouts/SwinjectStoryboard/Sources/SwinjectStoryboardOption.swift:12:17: note: do you want to add protocol stubs?
internal struct SwinjectStoryboardOption: ServiceKeyOption {
                ^

The cause of the error is the Swinject project moving to Swift 5 as part of their 2.7.0 release. Rolling back to Swinject 2.6.2 worked around the problem for me.

**Comment by adamayoung** [comment] 2019-09-25 08:44
Is there an ETA on a fix?

**Comment by lygialiem** [comment] 2019-09-30 07:45
I faced this issue. Just conform it and do not mofidy anything else in the Func which has just been added.

**Comment by Mustafa-Ezzat** [comment] 2019-10-13 12:29
Please add the following method:
    func hash(into: inout Hasher) {
        into.combine(self.controllerType)
    }
in
SwinjectStoryboardOption.swift
then 
release

**Comment by Panajev** [comment] 2019-10-16 12:30
Hello @jakubvano it seems like this fixes all the issues we had? Do you think it will go live/released soon?

**Comment by michzio** [comment] 2019-10-24 12:46
Yeas i have experienced this in Xcode 11 in latest SwinjectStoryboard library

**Comment by lauramejiaarroyave** [comment] 2019-10-24 21:59
T_T For those of us who use CI and we have the pods in the gitignore, what a problem, someone has news?

**Comment by Sega-Zero** [comment] 2019-10-24 22:12
It appears that master branch head contains this code already, there's just no update on cocoapods. so, those who use a CI for now may specify branch in Podfile.
Hope @yoichitgy or @jakubvano will release it soon =)

**Comment by pallzoltan** [comment] 2019-11-07 09:11
Clean checkout & build with carthage fails becuase it checks out commit [e687b47] tagged with `2.2.0`. @jakubvano, would you tag commit [0ca45c8] with `2.2.1`?

**Comment by lauramejiaarroyave** [comment] 2019-11-07 20:13
`Closed`  Pero no hacen merge del PR. :(

**Comment by ChaosCoder** [comment] 2019-11-23 11:23
Please release a new version (e.g. `2.2.1`) from `master`.

**Comment by sam-moshenko** [comment] 2019-11-27 18:48
I think a cleaner fix is to go to `Podfile.lock` and look for `Swinject`, set it's version to 2.6.0 instead of 2.7.x
As soon as `SwinjectStoryboard` releases a fix, you can just update the `SwinjectStoryboard` and I believe it will automatically update `Swinject`

**Comment by gilroykilroy** [comment] 2019-11-27 19:09
I respectfully ask is anyone paying attention anymore? This issue has existed for months already.

**Comment by dvshelley** [comment] 2019-11-27 22:11
@sam-moshenko You are right. That would work around the problem until a new release for SwinjectStoryboard is created.

But I think the bigger question is from @gilroykilroy about whether or not there is going to be another SwinjectStoryboard release. The code to fix the problem has been checked into master for quite a while. I'm really unclear when a release was not created when the code was merged?

**Comment by matthiasnagel** [comment] 2020-04-24 14:58
@jakubvano I just want to bring up this topic again. How can I help you releasing a new version with the fix?

**Comment by jcfrank77** [comment] 2020-05-27 09:28
Is there any expected ETA for this fix?  Seems like a pretty simple change that would fix 2.7.0?

**Comment by teejayhh** [comment] 2021-01-19 21:59
this is I still have this issue in 2021 the problem very much alive.

**Comment by sskjames** [comment] 2021-01-26 07:38
Still facing this issue. Using this as a temporary workaround:

    pod 'Swinject', '~> 2.7.1'
    pod 'SwinjectStoryboard', :git => 'https://github.com/Swinject/SwinjectStoryboard.git', :commit => '0ca45c83a8aa398c153d8a036c95abb4343cfa0c'

**Comment by mapo80** [comment] 2021-03-08 16:47
Can you fix this?

**Comment by mpdifran** [comment] 2021-07-16 01:32
Sorry for the late reply here! I've just released version 2.2.1 which should have a fix for this issue included. 

I'm going to close this issue for now, please reopen if the issue isn't actually fixed!

**Closed by mpdifran** 2021-07-16 01:32 UTC

**Comment by Bartson** [comment] 2021-08-10 11:08
Hi, the problem still exists on v2.2.1 :/
