### ISSUE TITLE
Circular Dependencies with UIViewController instantiating

### ISSUE THREAD

**Issue by igorkotkovets** [Swinject/SwinjectStoryboard#27] opened 2016-10-13 08:40 UTC
I'm following VIPER principles. And there are circular dependencies, for example between View(UIViewController)<->Presenter, Presenter<->Interactor.

How to resolve circular dependencies between UIViewController, for example 

``` swift
class LoginViewController: UIViewController, LoginViewInput {    
    var output: LoginViewOutput?

    override func viewDidLoad() {
        super.viewDidLoad()
        output?.didTriggerViewDidLoad();
    }

    func say(message: String?) {
        print(message)
    }
}

class LoginPresenter: LoginViewOutput {
    weak var view: LoginViewInput?

    func didTriggerViewDidLoad() {
        print("Did trigger View Did Load")
        view?.say(message: "Hello")
    }
}
```

I'm trying this way but it doesn't work

``` swift
import Swinject
import SwinjectStoryboard

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    var container: Container = {
        let container = Container()

        container.registerForStoryboard(LoginViewController.self) { r, c in
            c.output = r.resolve(LoginViewOutput.self)
        }
        container.register(LoginViewOutput.self) { _ in LoginPresenter() }
            .initCompleted { r, c in
                let presenter = c as! LoginPresenter
                presenter.view = r.resolve(LoginViewController.self)
        }

        return container
    }()


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        window.makeKeyAndVisible()
        self.window = window

        let storyboard = SwinjectStoryboard.create(name: "Main", bundle: nil, container: container)
        window.rootViewController = storyboard.instantiateInitialViewController()
        return true
    }
}
```

There is some discussion [here](https://github.com/Swinject/Swinject/issues/163)
Thanks

**Comment by jakubvano** [comment] 2016-10-13 17:04
Normal way of resolving circular dependencies when there are view controllers from `SwinjectStoryboard` involved is not supported - main problem is, that you cannot call `resolve` on those objects directly (as stated [here](https://github.com/Swinject/SwinjectStoryboard#usage)).

Another possibly confusing thing is the name of `registerForStoryboard` method, which looks like normal `register`, while it is semantically closer to `initCompleted` - this has been tackled in #22 .

As for your case, one way of resolving those circular dependencies would be:
```swift 
container.registerForStoryboard(LoginViewController.self) { r, c in
    c.output = r.resolve(LoginViewOutput.self, argument: c as LoginViewInput)
}
container.register(LoginViewOutput.self) { (_, view: LoginViewInput) in 
    let presenter = LoginPresenter()
    presenter.view = view
    return presenter 
}
```

**Comment by yoichitgy** [comment] 2016-11-24 11:44
@igorkotkovets, was the issue resolved?

**Comment by igorkotkovets** [comment] 2016-11-25 20:24
@jakubvano, @yoichitgy sorry for late answer. Could you explain how to resolve the dependencies between Interactor<->Presenter in this case? I've created a [sample project](https://github.com/igorkotkovets/swinject-viper) to show all 'login' module dependencies.

[AppDelegate](https://github.com/igorkotkovets/swinject-viper/blob/master/SwinjectViper/Modules/AppDelegate/AppDelegate.swift) creates the following 'Container' object

``` swift
var container: Container = {
        let container = Container()
        
        container.registerForStoryboard(LoginViewController.self) { r, c in
            c.output = r.resolve(LoginViewOutput.self, argument: c as LoginViewInput)
        }
        
        container.register(LoginViewOutput.self) { (_, view: LoginViewInput) in
            let presenter = LoginPresenter()
            presenter.view = view
            return presenter
        }
        
        return container
    }()
```

Thanks!

**Comment by yoichitgy** [comment] 2016-11-26 15:40
Does your question come from the condition where `LoginPresenter` implements both `LoginViewOutput` and `LoginInteractorOutput` protocols?

I didn't build your project, but I think you can get the dependency injected like below. You might need to modify some parts to build the code (because I didn't try).

``` swift
var container: Container = {
        let container = Container()
        
        container.registerForStoryboard(LoginViewController.self) { r, c in
            c.output = r.resolve(LoginViewOutput.self, argument: c as LoginViewInput)
        }
        
        container.register(LoginViewOutput.self) { (r, view: LoginViewInput) in
            let presenter = LoginPresenter()
            presenter.view = view
            presenter.interactor = r.resolve(LoginInteractorInput.self)!
            return presenter
        }

        container.register(LoginInteractorOutput.self) { r in
            r.resolve(LoginViewOutput.self) as! LoginInteractorOutput
        }
        
        container.register(LoginInteractorInput.self) { r in LoginInteractor() }
            .initCompleted { r, i in
                 let loginInteractor = i as! LoginInteractor
                 loginInteractor.output = r.resolve(LoginInteractorOutput.self)!
            }
        return container
    }()
```

Also, you might need to pass the container when you create SwinjectStoryboard instance because the code doesn't use `defaultContainer`.

**Comment by igorkotkovets** [comment] 2016-11-26 18:49
@yoichitgy, I've try your example above, but I get crash with resolving interactor.output dependency. 

![screen shot 2016-11-26 at 9 45 57 pm](https://cloud.githubusercontent.com/assets/1083951/20642521/00d15b3c-b422-11e6-87c0-56af8826afa7.png)

**Comment by yoichitgy** [comment] 2016-11-28 04:03
The example code needs to be fixed. Could you fix it?

**Comment by igorkotkovets** [comment] 2016-11-28 07:20
@yoichitgy, Is the issue in SwinjectStoryboard or you think in my example?

**Comment by yoichitgy** [comment] 2016-11-28 08:58
I think the issue is in the example code. I didn't build my example code in your project because it has a lot of "Run Script" phases, though I think they are added by CocoaPods without your intention. I didn't want to check all scripts that possibly ran when I built the project. So, the example I gave you was just a starting point.

If you find a bug in SwinjectStoryboard, I would appreciate your report or pull request😉

**Comment by yoichitgy** [comment] 2016-11-30 13:49
Although the architecture might be different from yours, this sample project using Swinject might be helpful for you:
https://github.com/ppamorim/swinjected

**Comment by yoichitgy** [comment] 2017-01-06 12:39
@igorkotkovets, was the problem resolved?

**Comment by igorkotkovets** [comment] 2017-01-10 07:05
@yoichitgy,

No problems with Swinject 2.0.0-beta.3

**Closed** 2017-01-10 07:06 UTC
Labels: question
