### ISSUE TITLE
[High Sierra] EXC_BAD_ACCESS within Swinjectstoryboard constructor

### ISSUE THREAD

**Issue by ohbargain** [Swinject/SwinjectStoryboard#73] opened 2017-09-20 00:36 UTC
https://github.com/Swinject/SwinjectStoryboard/blob/d727183ccbb8856e4b62758140352ca6e4f927e6/Sources/SwinjectStoryboard.swift#L73

Working on AppKit project using SwinjectStoryboard.

Upgraded to High Sierra GM candidate and the line above seem to cause problems. According to the comment in the code, the container box was placed in as a workaround for previous Xcode versions. 

I will try to investigate the problem and report back.

**Comment by dukhovnyi** [comment] 2017-09-20 07:27
@ohbargain its the same issue #69

**Comment by yoichitgy** [comment] 2017-09-20 09:42
Thanks @ohbargain for your investigation. PR is helpful if possible🙏

**Comment by ohbargain** [comment] 2017-09-20 15:04
I can't figure out what caused this. But creating and assigning any properties on SwinjectStoryboard class (Int, String, Class..) causes the crash.

**Comment by ohbargain** [comment] 2017-09-21 04:42
Also, this only seems to affect NSStoryboard. Not UIStoryboard. Test runs fine for iOS schemes.

**Comment by svetam** [comment] 2017-09-27 13:35
This is caused by the class method `[self storyboardWithName:name bundle:storyboardBundleOrNil]` which always returns `UIStoryboard`/`NSStoryboard` instances and not `SwinjectStoryboard` expected by the initialiser result. This instance is later cast to `SwinjectStoryboard` but it lacks `container` property at runtime.

Result is `EXC_BAD_ACCESS` in `SwinjectStoryboard.swift` in:
`public class func create(name: String, bundle storyboardBundleOrNil: Bundle?, container: Resolver) -> SwinjectStoryboard`
 
When trying to set `container` property:
`storyboard.container = Box(container)`

**Comment by kreeger** [comment] 2017-10-15 15:58
I'll note that I'm having this issue as well, and the workaround suggested in #69 does not work.

**Comment by jakubvano** [comment] 2018-02-14 13:14
I've been unable to reproduce the problem - do you guys still observe this issue, or has it been fixed by new version of tools?
My env: OSX 10.13.3, Xcode 9.2, Cocoapods 1.4.0, Carthage 0.28.0

**Comment by jakubvano** [comment] 2018-03-29 09:52
Proper support for Swift4 and iOS / OSX has been introduced in `2.0.0.-beta.1`.

Feel free to reopen this if issue still persists

**Closed by jakubvano** 2018-03-29 09:52 UTC
Labels: bug
